{
 "title": "SDK Metrics Java",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Failure %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(rate(temporal_request_total{}[5m]))\n  -\n  sum(rate(temporal_request_failure{}[5m]))\n)\n/\nsum(rate(temporal_request_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Task Slots Available (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(temporal_worker_task_slots_available{worker_type=\"WorkflowWorker\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Task Latency 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket[5m])) by (le, namespace, task_queue))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Task Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(temporal_workflow_task_schedule_to_start_latency_seconds_sum[5m])) by (namespace, task_queue)\n/\nsum(increase(temporal_workflow_task_schedule_to_start_latency_seconds_count[5m])) by (namespace, task_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Task Latency 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_activity_schedule_to_start_latency_seconds_bucket[5m])) by (le, namespace, task_queue))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Task Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(temporal_activity_schedule_to_start_latency_seconds_sum[5m])) by (namespace, task_queue)\n/\nsum(increase(temporal_activity_schedule_to_start_latency_seconds_count[5m])) by (namespace, task_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sticky Cache Size (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(max_over_time(temporal_sticky_cache_size{}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sticky Cache Evictions (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(temporal_sticky_cache_total_forced_eviction_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}